### ISSUE TITLE
Conflict with style guide and Default Formater

### ISSUE THREAD

**Issue by Nadezaxer** [FRC4607/BSOS#8]
The defalt formater formats a paragraph tag like this:
```
/**
 * Main initialization function. Do not perform any initialization here.
 *
 * <p>
 * If you change your main robot class, change the parameter type.
 */
```
But the styleguide (from #5) expects this: 
```
/**
 * Main initialization function. Do not perform any initialization here.
 *
 * <p>If you change your main robot class, change the parameter type.
 */
```

**Comment by ItsMajestiX** [comment]
> This is another module...and further experimenting shows that Checkstyle and the Formatter aren't compatible. I found a case where the fight one-another and I'm not interested in resolving this and all of the other discrepancies which will arise.

This is probably what Eric meant when he said the two formatters were fighting each other in #5. It seems like for now we will either have to remove `<p>` tags or fix the tags manually if we want to use the formatter, or just do formatting by hand.

**Comment by ghost** [comment]
Yup, this was what I found that pushed me to remove the formatter. This is is a non-issue using just Checkstyle.
